---
main:
  generator-tick-rate: 20  # ticks between generator spawns
database:
  database-path: database.sqlite
generators:
  types:
    iron-generator:
      material: minecraft:iron_block
      display-name: <grey>Iron Generator
      lore:
        - <light_grey>Generates iron ingots over time.
        - <light_grey>Place to activate.
      price: 10.0
      drop: iron-drop
    gold-generator:
      material: GOLD_BLOCK
      display-name: <gold>Gold Generator
      lore:
        - <light_grey>Generates gold ingots over time.
        - <light_grey>Place to activate.
      price: 20.0
      drop: gold-drop
  drops:
    iron-drop:
      material: IRON_INGOT
      display-name: <grey>Iron Ingot
      lore:
        - <light_grey>A precious metal obtained from iron generators.
      value: 10.0
    gold-drop:
      material: GOLD_INGOT
      display-name: <gold>Gold Ingot
      lore:
        - <light_grey>A precious metal obtained from gold generators.
      value: 20.0
